#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      return 0
      ;;
  esac

  local ver_calico="$(calico -v 2>/dev/null | perl -pe 's{^v}{}')"
  jq -n --arg calico "$ver_calico" '{calico: $calico}'
}

version "$@"
